name: AreaGuard
author: zand
main: com.zand.bukkit.areaguard.AreaGuard
version: 0.9.2_preview
commands:
  ag:
    description: Shows the help for areaguard
    usage: <command> help
  area:
    description: Shows the help for areaguard areas
    usage: <command> help
  cuboid:
    description: Shows the help for areaguard cuboids
    usage: <command> help
  agmain:
    description: Shows the help for areaguard
    usage: <command> help
  agarea:
    description: Shows the help for areaguard areas
    usage: <command> help
  agcuboid:
    description: Shows the help for areaguard cuboids
    usage: <command> help
  agadmin:
    description:
    usage: <command> help
  agdebug:
    description:
    usage: <command> help